baseurl = "https://www.datascienceblog.net"
title = "datascienceblog.net: R for Data Science "
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
# enable staticman comments (staticman.net)
StaticmanComments = "true"
disqusShortname = "datascienceblog-net" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
rssLimit = 20 # max nbr of entries shown in rss feed

[Author]
  name = "Matthias Döring"
  bio = "I've obtained a BSc and MSc in Bioinformatics from Saarland University. Currently, I am pursuing a PhD at the Max Planck Institute for Informatics where I'm researching computational methods for improving treatment and prevention of viral infections."
  avatar = "img/matthias_doering.jpg"
  url = "https://matthias-doering.netlify.com/"

[Params]
  subtitle = "Understand. Implement. Succeed." # Subtitle of your site
  description = "Interested in data science? Profit from this blog's comprehensive applications of statistical testing, machine learning, and visualization in R!"
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  post_navigation = true
  postSections = ["post"]
  mathjax = true # Enable MathJax

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

#[taxonomies]
  #category = ""
  #tags = ""

[menu]
    [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/post/"
    weight = 1

    [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about-data-science-with-R/"
    weight = 100

    [[menu.main]]
    name = "Resources"
    identifier = "blogroll"
    url = "/recommended-resources-data-science-and-R/"
    weight = 99

    [[menu.main]]
    name = "Contribute!"
    identifier = "contribute"
    url = "/contribute-to-datascienceblog/"
    weight = 102

    [[menu.main]]
    name = "RSS Feed"
    identifier = "RSS"
    url = "/post/index.xml"
    weight = 101


