baseurl = "https://www.datascienceblog.net"
title = "datascienceblog.net: R for Data Science"

languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "Mainroad"
# enable staticman comments (staticman.net)
StaticmanComments = "true"
#disqusShortname = "datascienceblog-net" # Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
rssLimit = 20 # max nbr of entries shown in rss feed

[Author]
  name = "Matthias Döring"
  bio = "I am currently working as a software developer at DB Systel where I'm supporting the digitalization of the German railway system. Previously, I completed my PhD at the Max Planck Institute for Informatics where I researched computational methods for improving treatment and prevention of viral infections."
  avatar = "img/matthias_doering.jpg"
  url = "https://matthias-doering.netlify.com/"

[Params]
  altTitle = "R for Data Science"
  downloadRmd = true
  contentPath = "https://www.github.com/rbind/data-blog/raw/master/content/"
  logoPath = "/img/datascienceblog_logo_wide_alt.png"
  subtitle = "R for data science: Understand. Implement. Succeed." # Subtitle of your site
  description = "Blog about data science with a focus on applications in R. Topics include statistical testing, machine learning, and data visualization. Find the answers to your questions!"
  opengraph = true # for social media links to blog
  twitter_cards = true # for twitter links to blog
  readmore = false # Show "Read more" button in list if true
  authorbox = false
  post_navigation = true
  postSections = ["post"]
  mathjax = true # Enable MathJax

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

[Params.staticman]
  comments_api = "https://staticmanbot.herokuapp.com/v2/entry/rbind/data-blog/master/comments" # was disabled due to spam
  polls_api = "https://staticmanbot.herokuapp.com/v2/entry/rbind/data-blog/master/polls"
  # recaptcha v2 sitekey and encrypted secret
  sitekey_V2 = "6LdZJ8MUAAAAAK5m-4z53KjV4rWTk8kY4FXtHwV4"
  secret_V2 = "P4bD88S7eebi4thAE3wDF2eQay+loQKhO6ObuvO02ZRXoAVfquKkhx7Y1aaMNGNZZ2ryM+lpKGehJq9LSGofjdvl/9IFS1v/t5wQ0uDMMcOwuLxJw9AWctCERN7BOzKPW5c9vPD3fLdLaFLKhDfz3aGNSqnOlqK8AcS2aojhB+YBLA1Pbn+NcGY0W4ffDmGyyMV/hN7nj35hCkyKIWPkGNCFFxr64L0SYmuws8o4rBTRFYi+mhoma5AzHWl3FcpyWnD5EWCE0zrkjKYFHBGM/xmEaRHjqwmnKFjUZcdIvQ9DqkNcPha/2C7RoYyMryDAEvxXc4v87wIPMRqDP8vtvA=="
  # TODO switch to staticman v3 for recaptcha v3 support
  # recaptcha v3
  sitekey_V3 = "6LejJsMUAAAAAGDlJ_02LI0Y8oQJmLpmbhsvxIED"
  secret_V3 = "dWg4uCDsrGT9vnrESuOg7tgOObPavc7b9a4AMn6ZnfN6fuXvHV09VRbS+dRf2uFTknwm+9JLhTjdf+oCeOtL32pXGnWQtW3wpRun8Sk6aA6PyU252ZGBn2XDm5AWHIT6UvFpA3Et4VYBnhqROt3+mh8S2PMBOLFO5RIH5QKrzuPYjo2anDFRGvdwPEzXAYKxfeBtxTWQNKeo7l0Sk06Ls5SrqNdmKYIcNjpoTpCfcQ2crJU9Z3u1UNxWCXLsAjiajpOpSbiTXZJ/R5XouOOsZcCTWV3l0DbvtSYC5hjQizAw4ILegFx8FZ3xP2EmuMzSybSv4vfKjPhgPZ2ZCNWH4A=="

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "poll"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  github = "matdoering"
  twitter = "matzedoering"
  linkedin = "matthias-doering"

#[taxonomies]
  #category = ""
  #tags = ""

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    url = ""
    weight = 1

    [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/post/"
    weight = 2

    [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about-data-science-with-R/"
    weight = 100

    [[menu.main]]
    name = "Resources"
    identifier = "blogroll"
    url = "/recommended-resources-data-science-and-R/"
    weight = 99

    [[menu.main]]
    name = "Contribute!"
    identifier = "contribute"
    url = "/contribute-to-datascienceblog/"
    weight = 102

    [[menu.main]]
    name = "RSS Feed"
    identifier = "RSS"
    url = "/post/index.xml"
    weight = 101


